// =============================================================================
// weights_bias_conv1.v – Conv1 Layer Weight and Bias ROM
// -----------------------------------------------------------------------------
// Layer: Conv1 (Regular Convolution)
// Kernel shape : (32, 1, 11, 7)  → 32 output channels, 1 input channel,
//                                   11 kernel rows, 7 kernel columns
// Weight count : 32 × 1 × 11 × 7 = 2464 INT8 values
// Bias count   : 32 INT16 values
//
// Weight address: addr = oc * 77 + kh * 7 + kw
//   oc  ∈ [0, 31], kh ∈ [0, 10], kw ∈ [0, 6]
// Bias address  : addr = oc  (0 .. 31)
//
// NOTE: The weight and bias values below are PLACEHOLDER values generated by a
// deterministic pseudo-random sequence.  Replace them with actual quantized
// INT8/INT16 parameters obtained from your quantization-aware training (QAT)
// flow before taping out.
//
// Interface:
//   w_addr  [11:0] → weight address (0 .. 2463)
//   w_data   [7:0] → INT8 weight output
//   b_addr   [4:0] → bias address (0 .. 31)
//   b_data  [15:0] → INT16 bias output
// =============================================================================
module weights_bias_conv1 (
    input  wire [11:0] w_addr,
    output wire signed [7:0]  w_data,
    input  wire  [4:0] b_addr,
    output wire signed [15:0] b_data
);

    // Weight ROM (2464 × 8-bit)
    reg signed [7:0] weights [0:2463];
    // Bias ROM  (32 × 16-bit)
    reg signed [15:0] biases [0:31];

    initial begin : init_weights
        integer i;
        integer x;
        // Deterministic LCG initializer (seed = 1) – replace with real weights
        x = 32'h00000001;
        for (i = 0; i < 2464; i = i + 1) begin
            x = (x * 32'd1664525 + 32'd1013904223) & 32'hFFFFFFFF;
            weights[i] = $signed(((x >> 16) % 9) - 4);
        end
        // All biases initialised to 0 (replace with trained bias values)
        for (i = 0; i < 32; i = i + 1)
            biases[i] = 16'sd0;
    end

    assign w_data = weights[w_addr];
    assign b_data = biases[b_addr];

endmodule
